name: easy_class
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  lottie: ^3.1.2
  google_generative_ai: ^0.4.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  flutter_html: ^3.0.0-beta.1
  html: ^0.15.4
  path: ^1.9.0
  get: ^4.6.6
  share_plus: ^10.0.2
  pdf: ^3.11.1
  open_file: ^3.5.5
  docx_template: ^0.4.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
flutter_native_splash:
  android: true
  ios: true
  web: false
  image: "assets/logo.png"
  color: "#FFFFFF"
  #android 12 versiya va undan yo'qori bo'lgan widgetlar uchun
  android_12:
    image: "assets/logo.png"
    color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/json/
    - assets/feedbacks.db
    - assets/svg_icon/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
